package iptables

import (
	"strings"
	"testing"

	"github.com/PotenFYR-Studios/FYRwall/internal/firewall"
)

// Fixtures mirror captured iptables-save output including UFW chains,
// malformed lines and an empty ruleset (spec section 40 fixtures).
const sampleSave = `# Generated by iptables-save
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:ufw-user-input - [0:0]
-A INPUT -s 203.0.113.5/32 -p tcp -m tcp --dport 22 -m comment --comment FYRWALL:RULE:ssh-admin -j ACCEPT
-A INPUT -p tcp -m multiport --dports 80,443 -m comment --comment 'web traffic rule' -j ACCEPT
-A INPUT -s 10.0.0.0/8 -i eth0 -o eth1 -j DROP
-A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
-A INPUT -p icmp -j ACCEPT
-A ufw-user-input -p tcp -m tcp --dport 25 -j DROP
COMMIT
# Completed`

func TestParseSaveBasicRules(t *testing.T) {
	rules := ParseSave(sampleSave)
	if len(rules) != 5 {
		t.Fatalf("expected 5 INPUT rules, got %d", len(rules))
	}
	first := rules[0]
	if first.Action != firewall.ActionAllow {
		t.Errorf("first rule action = %s, want allow", first.Action)
	}
	if first.Source != "203.0.113.5/32" {
		t.Errorf("source = %s", first.Source)
	}
	if first.Protocol != firewall.ProtoTCP {
		t.Errorf("protocol = %s", first.Protocol)
	}
	if first.DestinationPort != "22" {
		t.Errorf("dport = %s", first.DestinationPort)
	}
}

func TestParseSaveMultiport(t *testing.T) {
	rules := ParseSave(sampleSave)
	if rules[1].DestinationPort != "80,443" {
		t.Errorf("multiport dport = %q, want 80,443", rules[1].DestinationPort)
	}
}

func TestParseSaveConntrack(t *testing.T) {
	rules := ParseSave(sampleSave)
	if rules[3].State != "ESTABLISHED,RELATED" {
		t.Errorf("state = %q", rules[3].State)
	}
}

func TestParseSaveSkipsCustomChains(t *testing.T) {
	rules := ParseSave(sampleSave)
	for _, r := range rules {
		if r.Direction != firewall.DirIn {
			t.Fatalf("only INPUT rules expected in fixture, got %s", r.Direction)
		}
	}
}

func TestParseSaveEmptyRuleset(t *testing.T) {
	rules := ParseSave("*filter\n:INPUT ACCEPT [0:0]\nCOMMIT\n")
	if len(rules) != 0 {
		t.Fatalf("expected 0 rules from empty ruleset, got %d", len(rules))
	}
}

func TestParseSaveMalformedDoesNotCrash(t *testing.T) {
	garbage := "-A INPUT\n-A\n-A INPUT -p \x00binary\xffjunk -j DROP\nnot a rule at all\n-A INPUT -j\n"
	rules := ParseSave(garbage)
	// The binary junk line parses as DROP with no valid fields; acceptable.
	// The critical property is: no panic, and the unterminated -j is skipped.
	for _, r := range rules {
		if r.Action == "" {
			t.Fatalf("rule parsed with empty action: %+v", r)
		}
	}
}

func TestParseSaveQuotedComment(t *testing.T) {
	rules := ParseSave(sampleSave)
	found := false
	for _, r := range rules {
		if strings.Contains(r.Comment, "web traffic") {
			found = true
		}
	}
	if !found {
		t.Fatal("expected quoted comment with spaces to survive tokenization")
	}
}

func TestParseSave6Family(t *testing.T) {
	in := "-A INPUT -s fe80::/10 -p tcp --dport 22 -j ACCEPT"
	rules := ParseSave6(in)
	if len(rules) != 1 {
		t.Fatalf("expected 1 rule, got %d", len(rules))
	}
	if rules[0].Family != firewall.FamilyIPv6 {
		t.Errorf("family = %s", rules[0].Family)
	}
}
